Feat/58 monitoring
kimgunwooo/FQS-Flexible-Queue-Service pull request #65
Opened 2024-10-21 13:44 UTC by whitejh

### 👀 관련 이슈
- closed: 

### ✨ 작업한 내용

1. Prometheus, Grafana 모니터링 세팅
2. Loki 모니터링 세팅

### 🌀 PR Point

### 🍰 참고사항

### 📷 스크린샷 또는 GIF
|기능|스크린샷|
|:--:|:--:|
|||

2024-10-21 14:33 UTC, dragon0622 approved these changes
수고하셨습니다 !

2024-10-21 14:35 UTC, dragon0622 commented
근데 dev 브렌치말고 main 브렌치에 pr 인것같은데 괜찮은가요 ?

2024-10-21 14:42 UTC, J0minsu requested changes
Target branch main -> dev 수정 부탁드립니다!

2024-10-22 01:50 UTC, kimgunwooo approved these changes
확인했습니다.

2024-10-22 02:48 UTC, J0minsu approved these changes
고생하셨습니다

2024-10-22 02:48 UTC, merged