Feat/4 log in sign in
kimgunwooo/FQS-Flexible-Queue-Service pull request #9
Opened 2024-10-04 07:13 UTC by dragon0622

### 👀 관련 이슈
- closed: #4  

### ✨ 작업한 내용

jwt 로그인 및 회원가입을 구현했습니다.

### 🌀 PR Point

아직 jwt config 관련 설정이 덜 되어있고 기본적인 로그인 , 회원가입만 되어있습니다.
불필요한 메소드나 구조, 조금 더 나은 코드가 있으면 말씀해주세요 !

### 🍰 참고사항

### 📷 스크린샷 또는 GIF
|기능|스크린샷|
|:--:|:--:|
|||

2024-10-04 08:19 UTC, whitejh commented
확인했습니다

2024-10-04 08:20 UTC, whitejh approved these changes

2024-10-04 09:47 UTC, J0minsu requested changes
1. auth.userServiceClient 의 url 지우기
2. User service Spring validation @Valid 뒤 파라미터로 BindingResult 추가 후 hasError 시 검증로직 추가
3. CORS 확인

2024-10-04 09:47 UTC, kimgunwooo commented on service/auth/build.gradle
> +    annotationProcessor 'org.projectlombok:lombok'
루트 프로젝트에 lombok 설정이 존재해서 없어도 괜찮을 것 같습니다!!

2024-10-04 10:25 UTC, kimgunwooo approved these changes

2024-10-07 03:20 UTC, J0minsu approved these changes

2024-10-07 03:27 UTC, merged